### ISSUE TITLE
[Bug] Objects without any key can also be flatted, causing the control display to error

### ISSUE THREAD

**Issue by eric-gitta-moore** [eliasm307/storybook-addon-deep-controls#14]
Hi, I have solved this problem.

reproduce:
just
```ts
const meta = {
  component: YourComponent,
  argTypes: {
    style: { control: 'object' },
    'config.fetchParam': {
      control: 'object'
    },
    'config.jumpParam': {
      control: 'object',
    },
  } as ArgTypes,
  parameters: {
    deepControls: { enabled: true },
  },
} satisfies Meta<typeof YourComponent>;

export const Default: Story = {
  args: {
    data: {
      fetchParam: {}, // 1. will be fixed in this pr!
      jumpParam: {a:1}, // 2. There is still an issue that requires the user to explicitly set argTypes manually. fixed
    },
    style: {}, // 3. As predicted, showed
    data: {}, // 4. As predicted, argTypes must be set explicitly manually
  },
};
```

bug:
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/018a7b27-8f5c-402a-be32-24339a6d2e92">

Desired result:
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/2ec0eb87-ca11-4b43-80bb-af783016ef32">

**Comment by eliasm307** [comment]
@eric-gitta-moore thanks for raising this, I've considered the issue you raised and your PR and from what I can see there are 2 issues you are trying to address:

# 1 - An empty initial arg value will produce an object control with an empty object

You describe this as "causing the control display to error" however I don't agree its an error. I think preventing this happening means the addon will prevent some use-cases where the value can be any object. 

For example, if we look at the example you provided, there is a property called `style` which has an initial value as an empty object. I don't think it would be practical for initial values to be defined for every possible style, so an empty object control seems like the right thing for the user to customise the value however they want. An alternative is to explicitly define an `argType` so this shows as an empty object, however I think its just adding extra steps and also it is easy to make an error, e.g.  in the argTypes you defined 'config.jumpParam' but the value actually has 'data.jumpParam', so the argTypes will be creating a new unexpected object.

I think the experience is better and more accurate if the controls are inferred from the values, so I don't think we should hide empty objects as they could be intentional.

# 2 - An object with some of its properties defined with argTypes shouldn't be flattened

I got this from the changes in your PR, let me know if I have misunderstood.

This actually relates to the main example in the documentation, ie 

```
export const SomeStory = {
  args: {
    someObject: {
      anyString: "string",
      enumString: "string", // we only want specific values for this
    },
  },
  argTypes: {
    // so we define an argType for the property to use a radio control with specific values
    "someObject.enumString": {
      control: "radio",
      options: ["value1", "value2", "value3"],
    },
  },
};
```

Which produces:
![image](https://github.com/user-attachments/assets/3d7b0929-a6af-418d-aaa7-35890999fa3e)

If we made the change you suggest then this example would not flatten. I think its useful to be able to specify more specific types for some properties in an object and still have all the other properties flattened using the default logic, so I don't think we should make this change also.

I'm going to close this as wont do, however if you disagree please feel free to raise separate issue(s), one for each the 2 separate points above.
